// D-19b THIRD_PARTY_LICENSES.md generator. Shells `pnpm licenses list --prod
// --json`, drops machine-specific `paths`, flattens to {name, version, license}
// rows, sorts by name+version, and emits a deterministic Markdown table so the
// 06-06 `git diff --exit-code THIRD_PARTY_LICENSES.md` regen gate is stable
// across machines/runners (Pitfall 4). pnpm-native: zero new dependency.
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";

interface PnpmLicensePkg {
  name: string;
  version?: string;
  versions?: string[];
  license?: string;
}

// pnpm groups by SPDX license id; compound ids (e.g. "(MIT OR CC0-1.0)") are
// emitted verbatim — the AGPL gate (check-licenses.ts, 06-06) parses them, the
// generator only displays them.
// `pnpm` resolves to `pnpm.cmd` on Windows; Node blocks spawning a .cmd shim
// directly (CVE-2024-27980), so run through the platform shell. The command is
// a fixed literal with no untrusted input, so the shell form is safe; it lets
// the shell resolve the right `pnpm` on both win32 and CI Linux.
// Caveat: under a `corepack`-managed pnpm, `pnpm run licenses:generate` can
// fail to resolve THIS nested `pnpm` spawn (corepack PATH shimming). CI uses
// `pnpm/action-setup` (no corepack) so the regen-diff gate is green; if you
// hit it locally under corepack, run the script directly:
// `pnpm exec tsx scripts/gen-third-party-licenses.ts`.
const json = JSON.parse(
  execSync("pnpm licenses list --prod --json", {
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
    // pnpm prints a deprecation/advisory preamble to stderr on some setups;
    // keep stdout clean by ignoring stderr so JSON.parse never chokes.
    stdio: ["ignore", "pipe", "ignore"],
  }),
) as Record<string, PnpmLicensePkg[]>;

const rows: { name: string; version: string; license: string }[] = [];
for (const [license, pkgs] of Object.entries(json)) {
  for (const p of pkgs) {
    for (const v of p.versions ?? (p.version ? [p.version] : [])) {
      rows.push({ name: p.name, version: v, license });
    }
  }
}

// Dedupe (a package can surface under one license id once per version) and sort
// for byte-stable output. `paths` is intentionally never read — it is the
// machine-specific field that breaks the diff gate.
const seen = new Set<string>();
const unique = rows.filter((r) => {
  const k = `${r.name}@${r.version}@${r.license}`;
  if (seen.has(k)) return false;
  seen.add(k);
  return true;
});
unique.sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));

const md = [
  "# Third-Party Licenses",
  "",
  "Generated by `pnpm licenses:generate`. Do not edit by hand.",
  "",
  "| Package | Version | License |",
  "|---------|---------|---------|",
  ...unique.map((r) => `| ${r.name} | ${r.version} | ${r.license} |`),
  "",
].join("\n");

writeFileSync("THIRD_PARTY_LICENSES.md", md);
