import { describe, it, expect } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import enMessages from "../../messages/en.json" with { type: "json" };

// Paraglide i18n structure. Invariants:
//   - Paraglide message function resolves at runtime.
//   - Adding a locale = drop a JSON file (no source-code change).
//   - baseLocale only in MVP — no locale detection.
//   - Single messages/en.json at repo root.
//
// The locale-add invariant is preserved by the explicit alphabetical
// EXPECTED_KEYS list: a future PR adding a key without expanding this list
// trips the test loudly. The audit_action enum no longer carries
// `item.created` / `item.deleted` (renamed to event.*).
describe("paraglide i18n", () => {
  it("messages/en.json contains expected keys with the right English values", () => {
    const raw = JSON.parse(fs.readFileSync(path.resolve("messages/en.json"), "utf8"));
    expect(raw.dashboard_title).toBe("Promotion diary");
    expect(raw.login_button).toBe("Sign in with Google");
    expect(raw.sign_out).toBe("Sign out");
    expect(raw.sign_out_all_devices).toBe("Sign out from all devices");
  });

  it("m.dashboard_title resolves to English at runtime (when paraglide built)", async () => {
    // The compiled messages.js is gitignored. If present (CI runs `pnpm build`
    // first; local dev runs `pnpm dev` which compiles on demand), import it.
    // Otherwise this test is a contract assertion against the JSON.
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const mod: any = await import("../../src/lib/paraglide/messages.js" as string);
      expect(typeof mod.m.dashboard_title).toBe("function");
      expect(mod.m.dashboard_title()).toBe("Promotion diary");
    } catch {
      // Compiled output not available (test not run after build).
      // Assertion above on messages/en.json is sufficient for the unit-test gate.
    }
  });

  it("messages/en.json keyset matches the alphabetical contract (locale-add invariant)", () => {
    // The CONTRACT is: every locale file MUST share en.json's keyset.
    // This explicit alphabetical list IS the contract. A future PR adding a
    // key to en.json without extending this list trips the test; a future
    // PR adding a key to this list without extending en.json trips it too.
    // Adding a brand new locale is purely "drop a JSON file matching this
    // keyset" — no source change required.
    //
    // Asserting an explicit keyset (vs toMatchSnapshot) is more durable
    // across renames.
    const EXPECTED_KEYS = [
      "about_canonical_instance_label",
      "about_footer_contact",
      "about_footer_links_label",
      "about_hero_tagline",
      "about_intro_body",
      "about_links_privacy",
      "about_links_terms",
      "about_repo_link_label",
      "about_section_how_it_works_step_1_body",
      "about_section_how_it_works_step_1_title",
      "about_section_how_it_works_step_2_body",
      "about_section_how_it_works_step_2_title",
      "about_section_how_it_works_step_3_body",
      "about_section_how_it_works_step_3_title",
      "about_section_how_it_works_title",
      "about_section_open_source_body",
      "about_section_open_source_title",
      "about_section_privacy_body",
      "about_section_privacy_title",
      "about_section_self_host_body",
      "about_section_self_host_runbook_link",
      "about_section_self_host_title",
      "about_section_what_is_it_body",
      "about_section_what_is_it_title",
      "about_title",
      "account_deleted_banner_days_left",
      "account_deleted_banner_permanent_delete_button",
      "account_deleted_banner_permanent_delete_confirm",
      "account_deleted_banner_permanent_delete_failed",
      "account_deleted_banner_permanent_delete_pending",
      "account_deleted_banner_restore_button",
      "account_deleted_banner_restore_expired",
      "account_deleted_banner_restore_failed",
      "account_deleted_banner_title",
      "add_store_dialog_heading",
      "admin_layout_breadcrumb",
      "admin_layout_breadcrumb_aria",
      "admin_quota_audit_empty_body",
      "admin_quota_audit_empty_heading",
      "admin_quota_keys_empty_body",
      "admin_quota_keys_empty_heading",
      "admin_quota_load_failed",
      "admin_quota_page_intro",
      "admin_quota_page_title",
      "admin_quota_section_audit_title",
      "admin_quota_section_keys_title",
      "admin_quota_status_80_throttle",
      "admin_quota_status_95_throttle",
      "admin_quota_status_ok",
      "admin_quota_table_col_key_id",
      "admin_quota_table_col_pct_of_daily",
      "admin_quota_table_col_status",
      "admin_quota_table_col_units_used",
      "admin_reddit_adapter_degraded_chip",
      "admin_reddit_adapter_paused_chip",
      "admin_reddit_cap_exhausted_chip",
      "admin_reddit_col_count",
      "admin_reddit_col_dead_letter",
      "admin_reddit_col_lane",
      "admin_reddit_col_oldest",
      "admin_reddit_col_pending",
      "admin_reddit_col_processing",
      "admin_reddit_col_type",
      "admin_reddit_daily_block_intro",
      "admin_reddit_daily_block_title",
      "admin_reddit_daily_total_label",
      "admin_reddit_dead_letter_alarm",
      "admin_reddit_disabled_body",
      "admin_reddit_disabled_heading",
      "admin_reddit_lane_service_post",
      "admin_reddit_lane_service_source",
      "admin_reddit_lane_user_post",
      "admin_reddit_lane_user_source",
      "admin_reddit_queue_block_intro",
      "admin_reddit_queue_block_title",
      "admin_reddit_section_title",
      "admin_reddit_type_author_poll",
      "admin_reddit_type_post_batch",
      "admin_reddit_type_post_single",
      "admin_reddit_type_sub_poll",
      "app_title",
      "appheader_account_menu_aria",
      "audit_action_account_deleted",
      "audit_action_account_exported",
      "audit_action_account_restored",
      "audit_action_auto_import_deferred",
      "audit_action_all",
      "audit_action_event_attached_to_game",
      "audit_action_event_created",
      "audit_action_event_deleted",
      "audit_action_event_detached_from_game",
      "audit_action_event_dismissed_from_inbox",
      "audit_action_event_edited",
      "audit_action_event_marked_standalone",
      "audit_action_event_poll_refreshed",
      "audit_action_event_restored",
      "audit_action_event_unmarked_standalone",
      "audit_action_game_created",
      "audit_action_game_deleted",
      "audit_action_game_restored",
      "audit_action_key_add",
      "audit_action_key_remove",
      "audit_action_key_rotate",
      "audit_action_poll_failed",
      "audit_action_purge_completed",
      "audit_action_quota_limit_hit",
      "audit_action_quota_service_throttled",
      "audit_action_reddit_adapter_degraded",
      "audit_action_reddit_cap_exhausted",
      "audit_action_reddit_deletion_propagated",
      "audit_action_reddit_queue_drained",
      "audit_action_session_signin",
      "audit_action_session_signout",
      "audit_action_session_signout_all",
      "audit_action_source_added",
      "audit_action_source_refresh_content_requested",
      "audit_action_source_removed",
      "audit_action_source_toggled_auto_import",
      "audit_action_theme_changed",
      "audit_action_user_signup",
      "audit_filter_action_axis_label",
      "audit_filter_date_axis_label",
      "backfill_picker_helper_1d",
      "backfill_picker_helper_1y",
      "backfill_picker_helper_30d",
      "backfill_picker_helper_7d",
      "backfill_picker_helper_90d",
      "backfill_picker_helper_everything",
      "backfill_picker_preset_1d_label",
      "backfill_picker_preset_30d_label",
      "backfill_picker_preset_7d_label",
      "backfill_picker_preset_1y_label",
      "backfill_picker_preset_90d_label",
      "backfill_picker_preset_everything_label",
      "backfill_picker_section_blurb",
      "backfill_picker_section_title",
      "badge_purge_in_days",
      "badge_purge_in_days_warning",
      "badge_release_tba",
      "card_reddit_badge_mine",
      "card_reddit_metric_comments",
      "card_reddit_metric_score",
      "card_reddit_metric_upvote_ratio",
      "card_reddit_subtitle_mine",
      "card_youtube_badge_mine",
      "card_youtube_metric_comments",
      "card_youtube_metric_likes",
      "card_youtube_metric_views",
      "card_youtube_subtitle_mine",
      "common_cancel",
      "common_close",
      "common_confirm",
      "common_delete",
      "common_edit",
      "common_kind_reddit",
      "common_kind_reddit_subreddit",
      "common_kind_reddit_user",
      "common_remove",
      "common_restore",
      "common_save",
      "confirm_dialog_type_delete_label",
      "confirm_dialog_type_delete_placeholder",
      "confirm_event_delete",
      "confirm_game_delete",
      "confirm_item_delete",
      "confirm_key_remove",
      "confirm_key_replace",
      "confirm_listing_remove_body",
      "confirm_listing_remove_title",
      "confirm_signout_all",
      "confirm_source_remove",
      "confirm_speedbump_acknowledge",
      "dashboard_title",
      "dashboard_unauth_intro",
      "dashboard_welcome_intro",
      "empty_audit_body",
      "empty_audit_heading",
      "empty_events_body",
      "empty_events_heading",
      "empty_feed_body",
      "empty_feed_filtered_body",
      "empty_feed_filtered_heading",
      "empty_feed_heading",
      "empty_games_body",
      "empty_games_heading",
      "empty_items_example_youtube_url",
      "empty_items_heading",
      "empty_keys_steam_body",
      "empty_keys_steam_heading",
      "empty_sources_body",
      "empty_sources_heading",
      "empty_youtube_channels_body",
      "empty_youtube_channels_heading",
      "error_network",
      "error_server_generic",
      "event_edit_aria_label",
      "event_kind_label_conference",
      "event_kind_label_discord_drop",
      "event_kind_label_other",
      "event_kind_label_post",
      "event_kind_label_press",
      "event_kind_label_reddit_post",
      "event_kind_label_talk",
      "event_kind_label_telegram_post",
      "event_kind_label_twitter_post",
      "event_kind_label_youtube_video",
      "events_cta_new_event",
      "events_detail_delete",
      "events_detail_edit",
      "events_detail_open_original",
      "events_detail_charts_heading",
      "events_detail_charts_placeholder",
      "events_detail_restore",
      "events_edit_author_is_me",
      "events_edit_delete_button",
      "events_edit_games_empty",
      "events_edit_games_label",
      "events_edit_heading",
      "events_edit_save",
      "events_edit_standalone_conflict",
      "events_edit_standalone_help",
      "events_edit_standalone_label",
      "events_new_author_is_me",
      "events_new_date_today",
      "events_new_date_yesterday",
      "events_new_date_in_past_hint",
      "events_new_url_required",
      "events_new_fetch_button",
      "events_new_fetch_err_generic",
      "events_new_fetch_err_invalid_url",
      "events_new_fetch_err_network",
      "events_new_fetch_err_not_found",
      "events_new_fetch_err_rate_limited",
      "events_new_fetch_err_unavailable",
      "events_new_fetch_info_cached",
      "events_new_fetch_info_fresh",
      "events_new_fetch_loading",
      "events_new_fetch_title",
      "feed_attach_error_already_attached",
      "feed_attach_error_game_not_found",
      "feed_attach_no_games_inline",
      "feed_attach_to_game",
      "feed_card_attach_compact_label",
      "feed_card_author_is_me_badge",
      "feed_card_mark_standalone_button",
      "feed_card_open_external",
      "feed_card_reddit_baseline_insufficient",
      "feed_card_reddit_baseline_underperforming",
      "feed_card_reddit_stats",
      "feed_card_thumbnail_alt",
      "feed_chip_axis_action",
      "feed_chip_axis_kind",
      "feed_chip_axis_show",
      "feed_chip_axis_source",
      "feed_cta_add_event",
      "feed_cta_new_event",
      "feed_date_range_all_time",
      "feed_date_range_clear",
      "feed_date_range_label_from",
      "feed_date_range_label_to",
      "feed_date_range_month",
      "feed_date_range_today",
      "feed_date_range_week",
      "feed_date_range_year",
      "feed_deleted_panel_restore_aria",
      "feed_deleted_panel_restore_cta",
      "feed_deleted_panel_toggle_hide",
      "feed_deleted_panel_toggle_show",
      "feed_dismiss_error_not_in_inbox",
      "feed_dismiss_from_inbox",
      "feed_filter_author_me",
      "feed_filter_author_others",
      "feed_filter_chip_dismiss_aria",
      "feed_filter_game",
      "feed_filter_kind",
      "feed_filter_show_any",
      "feed_filter_show_axis_label",
      "feed_filter_show_inbox",
      "feed_filter_show_specific",
      "feed_filter_show_standalone",
      "feed_filter_source",
      "feed_filters_apply",
      "feed_filters_clear_all",
      "feed_loading_more",
      "feed_move_to_inbox",
      "feed_no_more_events",
      "feed_quick_nav_all",
      "feed_quick_nav_inbox",
      "feed_quick_nav_more_games",
      "feed_quick_nav_standalone",
      "feed_row_delete_aria",
      "feed_row_edit_aria",
      "footer_copyright",
      "footer_link_about",
      "footer_link_github",
      "footer_link_privacy",
      "footer_link_terms",
      "game_add_steam_listing_cta",
      "game_rename_cta_discard",
      "game_rename_cta_save",
      "games_cta_new_game",
      "games_detail_edit_cta",
      "games_edit_cancel_cta",
      "games_edit_description_empty",
      "games_edit_description_label",
      "games_edit_description_placeholder",
      "games_edit_dialog_heading",
      "games_edit_save_cta",
      "games_edit_title_label",
      "games_detail_events_empty",
      "games_detail_events_heading",
      "games_detail_section_events",
      "games_detail_section_game",
      "games_detail_section_stores",
      "inbox_badge",
      "inbox_badge_tooltip",
      "ingest_error_malformed_url",
      "ingest_error_notes_too_long",
      "keys_steam_cta_add_another",
      "keys_steam_cta_replace",
      "keys_steam_cta_save",
      "keys_steam_error_invalid",
      "keys_steam_error_label_exists",
      "legal_back_to_about",
      "login_button",
      "login_continue",
      "login_early_access_disclaimer",
      "login_page_title",
      "page_header_recently_deleted",
      "polling_badge_cold_days_ago",
      "polling_badge_cold_yesterday",
      "polling_badge_frozen",
      "polling_badge_hot",
      "polling_badge_manual",
      "polling_badge_pending",
      "polling_badge_throttled",
      "polling_badge_unavailable",
      "polling_refresh_now_aria",
      "polling_refresh_now_cooldown_tooltip",
      "polling_refresh_now_done",
      "polling_refresh_now_error",
      "polling_refresh_now_pending",
      "privacy_last_updated",
      "privacy_section_changes_body",
      "privacy_section_changes_title",
      "privacy_section_children_body",
      "privacy_section_children_title",
      "privacy_section_complaints_body",
      "privacy_section_complaints_title",
      "privacy_section_contact_body",
      "privacy_section_contact_title",
      "privacy_section_cookies_body",
      "privacy_section_cookies_title",
      "privacy_section_data_collected_body",
      "privacy_section_data_collected_title",
      "privacy_section_lawful_basis_body",
      "privacy_section_lawful_basis_title",
      "privacy_section_processors_body",
      "privacy_section_processors_title",
      "privacy_section_retention_body",
      "privacy_section_retention_title",
      "privacy_section_rights_body",
      "privacy_section_rights_title",
      "privacy_section_security_body",
      "privacy_section_security_title",
      "privacy_section_storage_body",
      "privacy_section_storage_title",
      "privacy_section_who_we_are_body",
      "privacy_section_who_we_are_title",
      "privacy_title",
      "recovery_dialog_empty",
      "recovery_dialog_heading",
      "settings_account_delete_button",
      "settings_account_delete_confirm_body",
      "settings_account_delete_confirm_title",
      "settings_account_delete_failed",
      "settings_account_export_button",
      "settings_account_export_failed",
      "settings_account_export_in_progress",
      "settings_account_grace_explainer",
      "settings_account_link",
      "settings_account_section_danger_title",
      "settings_account_section_export_blurb",
      "settings_account_section_export_title",
      "settings_account_section_purge_now_blurb",
      "settings_account_section_purge_now_title",
      "settings_account_title",
      "settings_credentials_heading",
      "settings_credentials_steam_link_label",
      "settings_cta_save",
      "settings_sessions_blurb",
      "settings_sessions_current_badge",
      "settings_sessions_heading",
      "settings_sessions_only_current",
      "settings_sessions_signout_one",
      "settings_theme_blurb",
      "settings_theme_heading",
      "sign_out",
      "sign_out_all_devices",
      "source_kind_label_discord_server",
      "source_kind_label_reddit_account",
      "source_kind_label_telegram_channel",
      "source_kind_label_twitter_account",
      "source_kind_label_youtube_channel",
      "source_kind_status_discord_server",
      "source_kind_status_reddit_account",
      "source_kind_status_telegram_channel",
      "source_kind_status_twitter_account",
      "sources_auto_import_off",
      "sources_auto_import_on",
      "sources_cta_new_source",
      "sources_cta_save_source",
      // refresh-content endpoint UI ("Pull new content" button + toast
      // variants on /sources/[id]).
      "sources_detail_pull_events_quota_exhausted",
      "sources_detail_pull_new_content",
      "sources_detail_pull_new_content_cooldown",
      "sources_detail_pull_new_content_error",
      "sources_detail_pull_new_content_pending",
      "sources_detail_pull_new_content_success",
      "sources_detail_pull_new_content_unsupported",
      "sources_detail_pull_platform_quota_exhausted",
      "sources_detail_pull_rate_limited",
      "sources_detail_pull_requests_quota_exhausted",
      "source_card_last_polled_never",
      "source_chip_auto_import",
      "source_coverage_caught_up",
      "source_coverage_has_more",
      "source_coverage_never_polled",
      "source_coverage_quota_exhausted",
      "source_detail_settings_auto_import",
      "source_detail_settings_owned_by_me",
      "source_detail_settings_title",
      "source_detail_target_invalid_future",
      "source_detail_target_label",
      "source_detail_target_save",
      "quota_banner_axis_items",
      "quota_banner_axis_requests",
      "quota_banner_lifetime",
      "quota_banner_no_limit",
      "quota_banner_reddit_limits_explainer",
      "quota_banner_reddit_not_configured",
      "quota_banner_reddit_post_refreshes",
      "quota_banner_reddit_service_load",
      "quota_banner_reddit_source_actions",
      "quota_banner_reddit_tab_title",
      "quota_banner_resets_in",
      "quota_banner_subtitle",
      "quota_banner_title",
      "sources_error_duplicate",
      "sources_error_duplicate_channel",
      "sources_error_duplicate_channel_soft_deleted",
      "sources_error_kind_not_yet_functional",
      "sources_error_no_youtube_keys",
      "sources_error_not_a_reddit_url",
      "sources_error_not_a_youtube_url",
      "sources_error_video_not_found",
      "sources_error_youtube_unreachable",
      "sources_kind_disabled_tooltip",
      "sources_new_reddit_disabled",
      "sources_new_reddit_input_hint",
      "sources_new_reddit_listing_limit",
      "sources_owned_by_me",
      "sources_owned_by_other",
      "sources_status_auto_off",
      "sources_status_auto_on_pending",
      "steam_listing_app_id",
      "steam_listing_cover_alt",
      "steam_listing_duplicate_active_link_label",
      "steam_listing_duplicate_active_prefix",
      "steam_listing_duplicate_soft_deleted",
      "steam_listing_edit_aria",
      "steam_listing_edit_save_cta",
      "steam_listing_kind_steam",
      "steam_listing_label_edit_label",
      "steam_listing_label_prefix",
      "steam_listing_open_in_steam",
      "steam_listing_open_link_label",
      "steam_listing_remove_aria",
      "steam_listing_unnamed",
      "stores_add_cta",
      "stores_empty",
      "stores_section_heading",
      "terms_last_updated",
      "terms_section_acceptable_use_body",
      "terms_section_acceptable_use_title",
      "terms_section_account_body",
      "terms_section_account_title",
      "terms_section_changes_body",
      "terms_section_changes_title",
      "terms_section_contact_body",
      "terms_section_contact_title",
      "terms_section_early_access_body",
      "terms_section_early_access_title",
      "terms_section_limits_body",
      "terms_section_limits_title",
      "terms_section_open_source_body",
      "terms_section_open_source_title",
      "terms_section_service_description_body",
      "terms_section_service_description_title",
      "terms_section_termination_body",
      "terms_section_termination_title",
      "terms_section_warranty_body",
      "terms_section_warranty_title",
      "terms_title",
      "theme_label_dark",
      "theme_label_light",
      "theme_label_system",
      "theme_toggle_aria_label",
      "toast_deleted",
      "toast_reddit_post_cap",
      "toast_reddit_source_cap",
      "toast_restored",
      "toast_saved",
      "youtube_channels_cta_add",
    ] as const;

    const keys = Object.keys(enMessages)
      .filter((k) => !k.startsWith("$"))
      .sort();
    expect(keys).toEqual([...EXPECTED_KEYS].sort());
  });

  it("removes audit_action_item_* keys (dead after enum rename)", () => {
    expect(enMessages).not.toHaveProperty("audit_action_item_created");
    expect(enMessages).not.toHaveProperty("audit_action_item_deleted");
  });

  it("PollingBadge + refresh-now + admin /quota copy lands the verbatim strings", () => {
    // These literals must match exactly. Drift here means the badge / page
    // now renders different copy than the design contract. The test is
    // structural-AND-content (keyset assertion above catches missing keys;
    // this catches accidental copy drift).
    const m = enMessages as Record<string, string>;
    // PollingBadge five live variants (Active / Cold ×2 / Frozen / Unavailable + Throttled).
    expect(m.polling_badge_hot).toBe("Hot · checked {hoursAgo}h ago");
    expect(m.polling_badge_cold_yesterday).toBe("Cold · yesterday");
    expect(m.polling_badge_cold_days_ago).toBe("Cold · {daysAgo}d ago");
    expect(m.polling_badge_frozen).toBe("Frozen · refresh to update");
    expect(m.polling_badge_unavailable).toBe("Unavailable · last seen {daysAgo}d ago");
    expect(m.polling_badge_throttled).toBe("Throttled — operator quota");
    // Admin-quota status pills (the load-bearing copy on /admin/quota).
    expect(m.admin_quota_status_80_throttle).toBe("80% throttle — Cold paused");
    expect(m.admin_quota_status_95_throttle).toBe("95% throttle — Active paused");
    // BackfillPicker per-preset helper copy (the load-bearing nudge text
    // on the source-creation form). Each preset has its own helper line
    // since both the date cutoff AND the 1000-event cap apply at once;
    // spelling them out per-preset avoids the "selected window" jargon
    // that confused users on 2026-05-06.
    expect(m.backfill_picker_helper_30d).toBe(
      "Last 30 days, up to 1000 events added to your feed.",
    );
    expect(m.backfill_picker_helper_everything).toBe(
      "Channel history, up to 1000 most recent events added to your feed.",
    );
    expect(m.backfill_picker_preset_everything_label).toBe("All");
  });

  it("deprecated polling_badge_phase3_placeholder key is removed", () => {
    expect(enMessages).not.toHaveProperty("polling_badge_phase3_placeholder");
  });

  it("project.inlang/settings.json has baseLocale=en and a single locale in MVP", () => {
    const settings = JSON.parse(
      fs.readFileSync(path.resolve("project.inlang/settings.json"), "utf8"),
    );
    expect(settings.baseLocale).toBe("en");
    expect(settings.locales).toEqual(["en"]);
  });
});
