// Pure parser for the Steamworks `Wishlists.csv` export (WISH-02).
//
// No DB, no balance derivation: the service layer derives the cumulative
// balance over the stored series — the parser returns RAW components only.
// Keeping it pure makes it trivially testable and reusable from both the
// import route and any future re-import path.
//
// Tolerance rules (the export is generated by Steamworks and varies):
//   - leading BOM (U+FEFF) stripped
//   - CRLF or LF line endings (split on /\r?\n/)
//   - blank / trailing-blank lines dropped
//   - extra trailing columns (e.g. a `MonthCohort` cohort column) ignored
//   - PREAMBLE before the header: the real export starts with a spreadsheet
//     hint line (`sep=,`) and a human title line (e.g. "Steam Wishlisting
//     data for 2026-04-23 - 2026-06-01") and a blank line BEFORE the column
//     header. We scan for the first line carrying every required column
//     rather than assuming the header is line 0 (confirmed against a real
//     SteamWishlists_{appid}_{from}_to_{to}.csv export).
//
// Header-NAME-driven, never positional: the unread `Game` column
// (index 1) can itself contain a comma-bearing title and an extra
// trailing column would shift any positional read. We map each required
// header to its index once and read cells by that index. `Game` is never
// read — its display name is owned by `game_steam_listings` (no
// denormalization), so the parser has no reason to touch it.
//
// RFC-4180 quoting: Steam quotes any field containing a comma (e.g. a game
// title like `"Portal: Companion, Vol. 2"`), so we tokenize with a quote-aware
// splitter — a naive split(",") would shift the numeric columns and silently
// skip every row. Embedded newlines inside quotes are not expected from this
// export (integers + ISO dates + a single title), so we still line-split first.

import { AppError } from "../services/errors.js";

export interface WishlistCsvRow {
  date: string; // YYYY-MM-DD (DateLocal), trimmed
  adds: number;
  deletes: number;
  purchasesAndActivations: number;
  gifts: number;
}

export interface WishlistCsvParseResult {
  rows: WishlistCsvRow[];
  skipped: number; // malformed data rows skipped (not aborted)
}

const REQUIRED = ["DateLocal", "Adds", "Deletes", "PurchasesAndActivations", "Gifts"] as const;

function invalidHeader(detail: string): never {
  throw new AppError(`wishlist_csv_invalid_header: ${detail}`, "wishlist_csv_invalid_header", 422);
}

// A missing or out-of-range cell yields NaN, which the caller treats as a
// malformed row (skip + count) — never a parse abort.
//
// STRICT parse: Number.parseInt("1,234") returns 1 and parseInt("5abc")
// returns 5 — silent corruption that is NOT NaN, so it would slip past the
// skip path. Match a whole-string non-negative integer first; anything else
// (thousands separators, trailing junk, empty, negatives) becomes NaN.
//
// Adds/deletes/purchases/gifts are non-negative counts and land in a Postgres
// int4 column, so reject negatives and anything above int4's max (overflow
// would surface as a DB error rather than a controlled skip).
const INT4_MAX = 2147483647;
function parseIntCell(cell: string | undefined): number {
  const s = (cell ?? "").trim();
  if (!/^\d+$/.test(s)) return NaN;
  const n = Number(s);
  if (n > INT4_MAX) return NaN;
  return n;
}

// A non-empty DateLocal cell still flows into a Postgres `date` column, so an
// invalid value (wrong shape OR a non-existent calendar day like 2026-02-30)
// would surface as a DB error rather than the controlled skip path. Require
// the canonical YYYY-MM-DD shape AND a round-trip through Date: a real day
// re-serialises to the same string, while 2026-13-01 / 2026-02-30 normalise to
// a different date and are rejected.
function isValidDate(date: string): boolean {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return false;
  const parsed = new Date(`${date}T00:00:00Z`);
  return !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === date;
}

// Quote-aware single-line CSV tokenizer (RFC-4180). A quoted field may contain
// commas; a doubled quote ("") inside a quoted field is a literal quote.
// Returns raw cells (callers trim where needed).
function splitCsvLine(line: string): string[] {
  const cells: string[] = [];
  let cur = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"') {
        if (line[i + 1] === '"') {
          cur += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        cur += ch;
      }
    } else if (ch === '"') {
      inQuotes = true;
    } else if (ch === ",") {
      cells.push(cur);
      cur = "";
    } else {
      cur += ch;
    }
  }
  cells.push(cur);
  return cells;
}

export function parseWishlistCsv(text: string): WishlistCsvParseResult {
  // Strip a leading BOM (U+FEFF) if present, then split on CRLF or LF and
  // drop blank / trailing-blank lines.
  const withoutBom = text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;
  const lines = withoutBom.split(/\r?\n/).filter((line) => line.trim() !== "");

  // Locate the header row by content, skipping any `sep=,` / title preamble.
  let headerCols: string[] | null = null;
  let dataStart = 0;
  for (let i = 0; i < lines.length; i++) {
    const cols = splitCsvLine(lines[i]!).map((cell) => cell.trim());
    if (REQUIRED.every((name) => cols.includes(name))) {
      headerCols = cols;
      dataStart = i + 1;
      break;
    }
  }
  if (!headerCols) {
    // Common wrong-file: the lifetime SUMMARY export (one row, OutstandingWishes
    // column) instead of the daily Wishlist Actions export. Give a specific
    // message so the user knows which file to grab.
    const lower = withoutBom.toLowerCase();
    if (lower.includes("outstandingwishes") || lower.includes("lifetime summary")) {
      throw new AppError(
        "wishlist_csv_is_lifetime_summary: got the lifetime summary; need the daily Wishlist Actions export",
        "wishlist_csv_is_lifetime_summary",
        422,
      );
    }
    invalidHeader(`no header row with required columns (${REQUIRED.join(", ")})`);
  }
  if (dataStart >= lines.length) invalidHeader("header found but no data rows");

  const index = {} as Record<(typeof REQUIRED)[number], number>;
  for (const name of REQUIRED) index[name] = headerCols.indexOf(name);

  const rows: WishlistCsvRow[] = [];
  let skipped = 0;

  for (const line of lines.slice(dataStart)) {
    const cells = splitCsvLine(line);
    const date = cells[index.DateLocal]?.trim();
    const adds = parseIntCell(cells[index.Adds]);
    const deletes = parseIntCell(cells[index.Deletes]);
    const purchasesAndActivations = parseIntCell(cells[index.PurchasesAndActivations]);
    const gifts = parseIntCell(cells[index.Gifts]);

    if (
      !date ||
      !isValidDate(date) ||
      Number.isNaN(adds) ||
      Number.isNaN(deletes) ||
      Number.isNaN(purchasesAndActivations) ||
      Number.isNaN(gifts)
    ) {
      skipped++;
      continue;
    }

    rows.push({ date, adds, deletes, purchasesAndActivations, gifts });
  }

  return { rows, skipped };
}
