// Pure parser for the Steamworks `Wishlists.csv` export (WISH-02).
//
// No DB, no balance derivation: the service layer (Plan 03.2-03) sorts the
// returned rows by date and derives the cumulative balance — the parser
// returns RAW components only. Keeping it pure makes it trivially testable
// against fixtures and reusable from both the import route and any future
// re-import path.
//
// Tolerance rules (the export is generated by Steamworks and varies):
//   - leading BOM (U+FEFF) stripped
//   - CRLF or LF line endings (split on /\r?\n/)
//   - blank / trailing-blank lines dropped
//   - extra trailing columns (e.g. a `MonthCohort` cohort column) ignored
//
// Header-NAME-driven, never positional (Pitfall 1): the unread `Game`
// column (index 1) can itself contain a comma-bearing title and an extra
// trailing column would shift any positional read. We map each required
// header to its index once and read cells by that index. `Game` is never
// read — its display name is owned by `game_steam_listings` (no
// denormalization), so the parser has no reason to touch it.

import { AppError } from "../services/errors.js";

export interface WishlistCsvRow {
  date: string; // YYYY-MM-DD (DateLocal), trimmed
  adds: number;
  deletes: number;
  purchasesAndActivations: number;
  gifts: number;
}

export interface WishlistCsvParseResult {
  rows: WishlistCsvRow[];
  skipped: number; // malformed data rows skipped (not aborted)
}

const REQUIRED = ["DateLocal", "Adds", "Deletes", "PurchasesAndActivations", "Gifts"] as const;

function invalidHeader(detail: string): never {
  throw new AppError(`wishlist_csv_invalid_header: ${detail}`, "wishlist_csv_invalid_header", 422);
}

// A missing or non-integer cell yields NaN, which the caller treats as a
// malformed row (skip + count) — never a parse abort.
function parseIntCell(cell: string | undefined): number {
  return Number.parseInt(cell ?? "", 10);
}

export function parseWishlistCsv(text: string): WishlistCsvParseResult {
  // Strip a leading BOM (U+FEFF) if present, then split on CRLF or LF and
  // drop blank / trailing-blank lines.
  const withoutBom = text.charCodeAt(0) === 0xfeff ? text.slice(1) : text;
  const lines = withoutBom.split(/\r?\n/).filter((line) => line.trim() !== "");

  if (lines.length < 2) invalidHeader("expected a header line and at least one data row");

  const header = lines[0]!.split(",").map((cell) => cell.trim());
  const index = {} as Record<(typeof REQUIRED)[number], number>;
  for (const name of REQUIRED) {
    const i = header.indexOf(name);
    if (i === -1) invalidHeader(`missing required column "${name}"`);
    index[name] = i;
  }

  const rows: WishlistCsvRow[] = [];
  let skipped = 0;

  for (const line of lines.slice(1)) {
    const cells = line.split(",");
    const date = cells[index.DateLocal]?.trim();
    const adds = parseIntCell(cells[index.Adds]);
    const deletes = parseIntCell(cells[index.Deletes]);
    const purchasesAndActivations = parseIntCell(cells[index.PurchasesAndActivations]);
    const gifts = parseIntCell(cells[index.Gifts]);

    if (
      !date ||
      Number.isNaN(adds) ||
      Number.isNaN(deletes) ||
      Number.isNaN(purchasesAndActivations) ||
      Number.isNaN(gifts)
    ) {
      skipped++;
      continue;
    }

    rows.push({ date, adds, deletes, purchasesAndActivations, gifts });
  }

  return { rows, skipped };
}
